- layouts/_default/baseof.html
Let's say your `.Site.Title` is "My Website". The code grabs `.Site.Title`, and then then checks to see if there's a `.Title`. When you're on the homepage, `.Title` is equivalent to `.Site.Title`, so that the browser bar will read:
> My Website | My Website
If we qualify `.Title` by confining it to the `.Params` namespace, then the site title isn't duplicated:
```<title>{{ block "title" . }}{{ .Site.Title }} {{ with .Params.Title }} | {{ . }}{{ end }}{{ end }}</title>```
> My Website
But it still picks up `.Title` from posts and pages, where a content title exists in front matter:
> My Website | About Me
> Don't duplicate site title in home page TITLE tag

- layouts/partials/social-follow.html
This allows for social links to be either inherited from config.toml, specific for each page, or completely disabled per page.
> Add inheritance for social links.

- layouts/_default/baseof.html
- layouts/partials/site-scripts.html
Hi @budparr,
https://themes.gohugo.io/theme/gohugo-theme-ananke/, a case where baseURL contains sub-folder, is not rendering correctly.  It appears that absURL behaves differently when the path is prefixed with a `/` slash.  The fix is to simply remove that leading slash.
The documentation at https://gohugo.io/functions/absurl/ does not seem to mention this fact explicitly.  Maybe we should fix the hugoDocs too.
See also #97
Thanks!
> Fix asset paths when baseURL has sub-folder

- layouts/partials/site-footer.html
This applies the flexbox directive `justify-between` to the nav items, not the icons themselves.
Fixes #127
> Add div to wrap social icons

- layouts/partials/site-header.html
This will allow the user to "blank" out the hero default set in the config. The if statement for blank was unreachable.
No changed needed to example site as the featured image is correctly specified in the front matter.
> Removed hardcoded theme sample hero image.

- i18n/de.toml
- i18n/en.toml
- layouts/index.html
- layouts/partials/menu-contextual.html
- layouts/partials/summary-with-image.html
With this Draft PR I want to get early feedback on my approach for tackling #108 and I would really appreciate some feedback from @budparr, @regisphilibert and anyone else involved.
I implemented a few strings that are easily visible but that should also include most of the strings. This theme is actually quiet and there isn't much text to translate in the first place I think.
I switched to this branch for my own blog and you can see the changes live at: https://blog.jan-steinke.de
So far I only have the translations for "de"(German) and "en"(English). The multi language support build into Hugo should default to "en" if I can trust [the documentation](https://gohugo.io/content-management/multilingual/#configure-languages), I haven't actually checked if this is true but it should make sure …
> add i18n translation support

- layouts/partials/menu-contextual.html
In English, the translation that is supposed to be shown on top of the table of contents looks like this:
```toml
[whatsInThis]
other = "What's in this {{.Type }}"
```
When it is invoked, I think that something is wrong in the calling code: `{{ i18n "whatsInThis" humanize .Type }}`.
This should be called `{{ i18n "whatsInThis" . }` instead because then the i18n can access the `.Type`; otherwise you get a `<no value>` output.
> Fix TOC header

- i18n/de.toml
- i18n/en.toml
- i18n/es.toml
- i18n/fr.toml
- i18n/nl.toml
- i18n/pt.toml
- i18n/ru.toml
- i18n/zh.toml
- layouts/shortcodes/form-contact.html
I translated the static text in the form-contact.html shortcode to all supported langages.
German is my mother tongue, the rest I translated with [DeepL](https://www.deepl.com/translator) (except for Chinese, there I had to use Google Translate).
This fixes #184
> localization for form-contact.html shortcode

- layouts/_default/baseof.html
These have been deprecated by Google
> Remove Google News meta tags

- README.md
As per https://gohugo.io/getting-started/quick-start/ I think it is better to use git submodules rather than cloning the repo. It should be easier to keep up to date etc. So please consider this change in documentation
> Use git submodules

- layouts/_default/baseof.html
Follows the template in the Hugo documentation [here](https://gohugo.io/templates/output-formats/). 
The issue is that calling `.OutputFormats.Get` returns a JSON blob. This was rendered as an `href` attribute, thus causing the error.
> Fixes #212

- layouts/_default/single.html
See #113
This adds an author to the blog page only.
Implementation mostly based on Docsy's version.
https://github.com/google/docsy/blob/master/layouts/blog/content.html
> Adds an author to blog posts.

- layouts/index.html
- layouts/partials/site-navigation.html
- layouts/partials/summary-with-image.html
- layouts/partials/summary.html
- layouts/post/summary-with-image.html
- layouts/post/summary.html
Using the `{{ .URL }}` token results in a warning:
WARN 2019/10/13 15:12:12 Page's .URL is deprecated and will be removed in a
future release. Use .Permalink or .RelPermalink. If what you want is the
front matter URL value, use .Params.url.
Follow along with the Quick Start guide at
https://gohugo.io/getting-started/quick-start/
Running `hugo server -D` emits a warning that `.URL` is deprecated.
> Replace {{ .URL }} with {{ .Permalink }}

- README.md
- exampleSite/content/contact.md
- stackbit.yaml
- theme.toml
This PR adds Stackbit configuration for users to easily use the theme through Stackbit's interface. https://www.stackbit.com
Fixes #200
> Add Stackbit Configuration

- README.md
The heading says "Word Contributing"  where it should say "Word Count"
> Fix word count heading typo in README.md

- i18n/zh.toml
Some original translations are not universal Simplified Chinese.
> Correct the original translation

- layouts/partials/svg/slack.svg
- src/css/_social-icons.css
The hover color is still not working, but now the icon size matches the others:
> Fix Slack icon size

- layouts/_default/single.html
In case the author parameter is a []string, which is the default for ox-hugo
output.
> Fix to take care of multiple author list

- README.md
- layouts/_default/single.html
> Font not applying to blog posts

- layouts/partials/site-navigation.html
- layouts/partials/social-share.html
This is basically a completion of #216
> Replace another 2 .URL occurrences with .Permalink

- layouts/partials/site-navigation.html
This way, when you click on the header it maintains you in the same language you previously selected.
> Use | relLangURL for the base url in the site-navigation

- layouts/_default/baseof.html
The way relURL was used meant that one needed to preface the custom_css
entries with a slash, or the href would be incorrectly set to
subdircss/mycss.css rather than subdir/css/mycss.css, in the case of
a baseURL in a subdir.
> Fix relURL for custom_css

- layouts/partials/site-favicon.html
This fixes sites which have the baseURL in a subdirectory.
> Use relative URL for favicon

- i18n/bg.toml
- i18n/de.toml
- i18n/en.toml
- i18n/es.toml
- i18n/fr.toml
- i18n/it.toml
- i18n/nl.toml
- i18n/pt.toml
- i18n/ru.toml
- i18n/sv.toml
- i18n/uk.toml
- i18n/zh.toml
- layouts/_default/taxonomy.html
> Add translation for taxonomy page

- layouts/_default/single.html
The existing template code results in the + chartering being written in a form that is not valid for the datetime element when used in and <time> tag.
This patch fixes this issue.
references:
https://discourse.gohugo.io/t/date-lastmod-return-43-in-place-of/27033
https://github.com/gohugoio/hugo/issues/7488
> Fix '+' character being written as &#43;

- layouts/_default/baseof.html
I use this template and I realized via Google Lighthouse that the `<meta name="description" content="">` 
tag was missing. Also, I updated the link to the internal templates doc.
- Update comments about internal templates
- Add missing meta description for SEO
Let me know if the PR needs more work.
> Update baseof template

- layouts/partials/i18nlist.html
When not using the configured URL then this breaks (e.g. using branch/PR deployments on netlify).
> use RelPermalink for i18n menu

- README.md
~~The user's module system may not be initialised. It should be initialised first, otherwise the user will be prompt with:~~
```
Error: module "github.com/theNewDynamic/gohugo-theme-ananke" not found; either add it as a Hugo Module or store it in "/path/to/dir/themes".: module does not exist
```
The above issue has been fixed by ce48112de29f91330ec4da2bfb7ed14d0ee1a19f, the PR has been updated.
The code snippet did not specify that yaml syntax was used instead of the default toml syntax. Changed it to toml syntax to avoid confusion.
> Fix confusion in README.md

- layouts/robots.txt
My understanding of how **robots.txt** are interpreted by search engines is that they should be explicitly *allowed* to parse the site ([source](https://developers.google.com/search/docs/advanced/robots/robots_txt?hl=en#allow)). Moreover, Google, Bing uses the `sitemap` entry in **robots.txt**. Here, the path is assembled with `{{.Site.BaseURL}}`
> fix : production should Allow and point to Sitemap

- layouts/index.html
- layouts/partials/func/GetFeaturedImage.html
- layouts/partials/social-share.html
- layouts/partials/summary-with-image.html
- layouts/partials/summary.html
- layouts/post/summary-with-image.html
- layouts/post/summary.html
I just submitted a PR for the language picker to have relative URLs because that was a thing I was working on then. I just recently found that other sections are also using the Permalink.
This PR replaces all usage of `.Permalink` with `.RelPermalink`. I setup a test website for this here: https://5f88ad34a2750b00077a188b--janxyz.netlify.app
Without the change references like links to Posts would point to the production version on `jan-steinke.de` and that was annoying to test new things as URLs needed manual intervention. This should fix that problem.
> enable hosting the website also on other URLs

- exampleSite/config.toml
- layouts/_default/single.html
If the author is not specified in the front matter, it is taken from the config file.
> Add default author.

- layouts/_default/single.html
The current template that parses articles will set a date of January 1, 0001 if the date is not defined in the md file. This PR wraps the date template in a conditional to check if the date has been set. If the date is not set the template will render the article without a date.
> Only print article date if it is non-zero

- archetypes/default.md
With Hugo v0.88.1 and earlier, ContentBaseName and TranslationBaseName
both returned "index" when creating a leaf bundle with hugo new. This is
a known bug, addressed with https://github.com/gohugoio/hugo/pull/9045.
With this PR:
hugo new post/my-first-post/index.md
will produce:
title: "My First Post"
instead of:
title: "Index"
> Base content title on ContentBaseName

- README.md
- layouts/partials/func/GetFeaturedImage.html
We look for .Params.featured_image
If found > we use that as URL
If we find a Page resource matching the value of the above, we use its .RelPermalink
If none of the above we look for an resource whose filepath contains `featured` or `cover` and use its .RelPermalink if found
Fixes #233
Fixes #407
Thanks to @sgharms @pmorch
> Featured image detection refactoring:

- i18n/zh-tw.toml
- i18n/zh.toml
The old translations was "What's this" instead of "What's in this"
> Fix zh* translation

- layouts/partials/site-header.html
Updates the site-header partial's featured_image logic to call the GetFeaturedImage partial so that it's consistent with the homepage and the page-header partial.
Closes #473
> Standardize featured_image logic

- i18n/de.toml
The phrase was only present in English.
> Add German translation for taxonomyPageList

- assets/ananke/css/_styles.css
- layouts/partials/tags.html
> 433 fix tags layout

- exampleSite/config.toml
- exampleSite/go.mod
- exampleSite/go.sum
- go.mod
We now use the them repo (branch `demo`) for https://gohugo-ananke-theme-demo.netlify.app/
Fixes #515
> Use theme repo for demo site

- layouts/page/single.html
Fixes #522
Came to my attention that the section would never be useful. Pages are most often at the root of the content directory `/content/about.md`, so the section would be the homepage.
If the page sits in `about/staff.md` then the default type would be `about` and not `page` thus not picking up the `single/page.md`.
The current implementation will blindly print the name of the directory in which belong the page which makes it impossible to localize.
> Remove Section mention from single/page

- i18n/de.toml
- i18n/en.toml
- i18n/es.toml
- i18n/fr.toml
- i18n/it.toml
- i18n/no.toml
- i18n/pt.toml
- layouts/_default/by.html
- layouts/_default/single.html
If an author is set the page will mention them with the with the "By" preposition which had never been localized. I've proceeded to add it for the languages I'm familiar with. 
If you've been mentioned in the following checklist, this means I identified you as the kind person(s) who initially or most recently updated the language's localization. Would you be kind enough to add you suggestion in the comments using this simple format: EN: `By` 
If you have any reservations, for example the preposition needs to agree with gender or number in the given language, please let me also know in the comments.
Thank you all!
Fixes #528
> Localize "By"

- README.md
- layouts/partials/social-follow.html
> Enable/Disable Social follow/share per service

- layouts/_default/summary-with-image.html
- layouts/partials/func/GetFeaturedImage.html
- layouts/partials/page-header.html
- layouts/partials/site-header.html
- layouts/partials/summary-with-image.html
This will solve the subdirectory edge case without communication
Fixes #556
> Only apply the absURL on images served through satic directory

- layouts/_default/terms.html
- layouts/partials/site-footer.html
- layouts/partials/tags.html
- layouts/robots.txt
This PR makes a few changes to improve the links generated by the theme templates:
1. use `absURL` to create the sitemap URL rather than concatenating with `.Site.BaseURL`. This avoids a non-canonical URL if BaseURL ends in a slash.
2. use `.GetTerms` to get a list of the tags for the page. This returns a list of page objects that know their URL.
3. use `.Data.Pages` to enumerate the terms in a taxonomy rather than `.Data.Terms`. Again, this lets Hugo generate the appropriate URL.
I noticed (2) and (3) in a Google search console report for my site, where the existing templates generate links without a trailing slash, resulting in a redirect. Letting Hugo generate the links itself avoids the problem. It also seems to work correctly with multi-lingual sites, after clicking around in the …
> Improve links for sitemap and taxonomies

- layouts/_default/baseof.html
> html[lang]: use  `site.Language.Lang` when `languageCode` is not set.

- README.md
- layouts/_default/baseof.html
When you want to publish content that is already published on a different site. You need to reference a canonical url of the original content. By defining the `canonicalUrl` in the front matter definition the canonical url is set in the headers.
> feat: add canonical url support

- layouts/_default/single.html
Currently `layouts/_default/single.html` uses `{{with .CurrentSection.Title }}{{. | upper }}{{end}}` to change the section title to ALL UPPERCASE.
This is bad for accessibility, because screen readers are likely to read POSTS as "pee oh ess tee ess".
The right thing to do if you want something to be displayed in all caps is to use CSS `text-transform`. This PR fixes the template to do that. Happily Tachyons has [a class for the purpose](http://tachyons.io/docs/typography/text-transform/), so the template code ends up being simpler.
> Fix capitalization of single page section header for a11y

- layouts/_default/summary.html
- layouts/post/summary.html
The `summary.html` template is missing the "read more" link that's in `summary-with-image.html`. The headings on a summary.html page have nothing to indicate that they are clickable -- no color variation, no underlining -- so it looks like there's nothing more than the heading and summary.
This adds the missing "read more" link so people know there's an entire article/post to read.
(Edit: Also fixes the post-specific `summary.html`)
> Add missing "read more" link to summary.html

- README.md
- layouts/_default/single.html
Prepare for deprecation described [here](https://github.com/gohugoio/hugo/commit/2eca1b3cc1cd03fee40c0abcdc61dab1016c0475).
This is a backwards compatible change.
> Access Disqus shortname from canonical location

- layouts/_default/baseof.html
This patch includes a `<meta name="author" ...` tag. If there are multiple authors, their names will be comma-seperated.
> Include authors meta tag

- layouts/index.html
#664  describes it.
https://github.com/theNewDynamic/gohugo-theme-ananke/blob/c086834f0ebfa39b8b6b0cfed010588a6907a91c/layouts/index.html#L13C31-L13C31
At the moment, only the first mainsection will be shown in the index.
I changed it so that the mainsections will be iterated with "range $mainsections".
This allows that multiple sections are possible and can be displayed.
>  Contribution: fix hard-coded link to section #664 

- layouts/_default/baseof.html
As of Hugo v0.122.4, these are equivalent:
```
{{ site.LanguageCode | default site.Language.Lang  }}
{{ site.Language.LanguageCode }}
```
See <https://gohugo.io/methods/site/language/#methods>
> refactor: Simplify lang attribute in html element

- README.md
- exampleSite/config.toml
- layouts/partials/page-header.html
- layouts/partials/site-header.html
Please provide enough information so that others can review your pull request:
Currently, the header image for a post is `bg-top`, but it would be nice the control this behavior to lets say `top|center|bottom`, as often the interesting part of an image is in the center. Using the `featured_image_class` param, one can now customize the class to control the alignment of the featured header image. It is also possible to add additional classes for further customization if needed.
Explain the **details** for making this change. What existing problem does the pull request solve?
**Test plan (required)**
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Default case:
Same as default case but set explicitly …
> Add control over header image

- README.md
- exampleSite/config.toml
- layouts/partials/page-header.html
- layouts/partials/site-header.html
- feature already present for site
- add info for the param to the example
Please provide enough information so that others can review your pull request:
Like https://github.com/theNewDynamic/gohugo-theme-ananke/pull/702, this PR wants to add the cover class to the page as well, but adds also the documentation to the example and allows both for page params and site params.
Explain the **details** for making this change. What existing problem does the pull request solve?
Solves https://github.com/theNewDynamic/gohugo-theme-ananke/issues/696 in a proper way for site and page with fallback and documentation in the example.
**Test plan (required)**
Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Default: …
> complete the feature for the cover dimming class in page

- exampleSite/config.toml
Add missing `params` prefix on `params.ananke.social.follow` when used in config.toml or hugo.toml.
> Add missing params on ananke.social.follow

- layouts/partials/social/share.html
Do NOT use the same cache name for social _share_ and social _follow_..
This will never work of course.
> Fix social share cache

- layouts/partials/social/share.html
You definitely want to **add Plainify transformer first**, because the body content will become a HTML encoding mess. I left `HTMLEscape` there as well, just be sure for security reasons. But if you want, I can remove the second transformer.
Like a tweet on X will look like this:
After implementing `transform.Plainify`, it will look much better:
(ignore the red, I don't have X premium pro blabla, it's red because I hit the max limit of chars)
> Add transform.Plainify to the summary body content of the share links

- layouts/partials/social/share.html
You can't just cache the share links, that will result into every blog post having the same URL.
Just use `partial` on the getShareLink.html. So now each post will show the correct URL to share the post via social media or alike.
> Do not cache share links

- layouts/partials/func/social/getShareLink.html
In these cases the site permalink is used instead of the social network URL for sharing as defined in the `link` value
(https://www.linkedin.com/shareArticle in the below example)
Most visible case is LinkedIn but all social networks that have
```toml
[ananke.social.networks.particles]
...
params = "..."
```
in `config/_default/params.toml` are affected by this bug.
Closes #768.
> Fix share link building when `params` particle is present

- config/_default/params.toml
- layouts/index.html
Closes #794
You can no longer set `recent_posts_number = 0` because in current hugo versions `{{ $n_posts := $.Param "recent_posts_number" | default 3 }}` will default to three if recent_posts_number is 0. This used to work a couple of versions back, I am assuming this is not a regression but rather wanted behavior in hugo -- so I introduce a new parameter (boolean) `show_recent_posts` to enable(default) or disable recent posts on index.
> Fixes #794 - add show_recent_posts parameter to stop showing recent posts on index

- i18n/oc.toml
Hello,
I hope this PR is well formed
Regards
> i18n: Create Occitan translation
