theNewDynamic/gohugo-theme-ananke

- README.md
> keeping things in order

- layouts/_default/list.html
Pagination doesn't actually work -- it just shows the pagination nav and the content repeats over and over. 
This commit fixes pagination.
> Fix pagination

- layouts/_default/baseof.html
I don't know if it's the right way to address this issue, but it works in both server mode and publishing mode.
> Use relative url function for custom CSS files

- layouts/partials/site-header.html
60% dimming does not look great on all images. The ability to change that would be awesome!
> Make cover dimming class customisable.

- README.md
I'm new to Hugo and it wasn't straightforward to find the right file to see the image example.
> Add explicit path to image example

- layouts/partials/social-follow.html
Keep in spirit with https://medium.com/@svinkle/why-let-someone-know-when-a-link-opens-a-new-window-8699d20ed3b1 but address issue #145
> Improve social link accessibility

- layouts/_default/list.html
- layouts/_default/single.html
- layouts/post/list.html
> Improve semantic structure of pages

- layouts/_default/single.html
> Keep article padding throughout widths

- layouts/index.html
Thanks for a great theme!
Super small PR for a thing i had to modify when attempting localization. Not sure of the name but it's in line with the `read_more_copy` in [summary-with-image.html](https://github.com/budparr/gohugo-theme-ananke/blob/85d9218877aea3f0f35fe7a887f714e09c2bc4fe/layouts/partials/summary-with-image.html#L23)
> Enable localization/modification of "Recent" string

- layouts/partials/page-header.html
- layouts/partials/site-header.html
- layouts/partials/site-navigation.html
> Correcting issue with cached i18n menu

- i18n/nl.toml
Hi,
Thank you for creating this theme. I added a Dutch translation file, that you might want to include.
> Dutch translations.

- i18n/es.toml
Hello,
Thank you for this theme. I have prepared a Spanish translation for it.
> Spanish Translation

- i18n/ru.toml
Hey there!
Added translation to Russian.
Thanks for a great theme.
> Add RU translation

- README.md
- layouts/_default/single.html
- layouts/partials/commento.html
Added configurable option to use https://commento.io/ block.
Sorry, my editor auto-removed some trailing whitespaces.
> Add commento

- i18n/pt.toml
Portuguese translation. I've just updated by comparing to the English en.toml and Spanish es.toml.
> Add portuguese translation

- stackbit.yaml
As per Simon, in Slack.
Fixes #224
> Fix stackbit issues

- package-lock.json
- package.json
This change will make it easier for maintainers to keep the changelog up-to-date.
https://github.com/CookPete/auto-changelog
> Add auto-changelog

- layouts/partials/site-navigation.html
Reverts https://github.com/budparr/gohugo-theme-ananke/commit/0d9656d939b58a1ea721b8cde42ef186514f00c3#diff-5c3a1b4da16de002912dd90a78641f32R12
Fixes #229 #220
> Fix URL for menus

- i18n/it.toml
Add file it.toml with italian translation
> Add italian translation

- layouts/partials/site-footer.html
Hello and thanks for this amazing theme!
It looks like the modifications discussed at #199 didn't go through, so here they are again.
Cheers
> Use Hugo's built in Site Config for copyright according to PR #199

- layouts/_default/single.html
> Safari Reader View lacks content

- layouts/_default/baseof.html
> Modify the title format

- README.md
> Not all config settings included in website build

- README.md
Hugo can read the Windows environment variables just fine, but you can't set the command & run on a single line (unless you use `&&` in between commands)
This will work for cmdline line. I can add a PowerShell version if there's interest.
Fixes #153
> Updated Windows instructions in README.md

- i18n/bg.toml
Translated to Bulgarian (Български).
> adding Bulgarian translation

- layouts/shortcodes/form-contact.html
I found a typo in form-contact.html, so I fixed it.
> Fixed a typo in form-contact.html

- README.md
- layouts/_default/baseof.html
> Add head partial

- i18n/es.toml
> Update spanish translations

- i18n/pt.toml
Hello,
I added a couple of changes to the Portuguese translations. First, I changed the _recentTitle_ translation to something that sounds better and later I updated the _taxonomyPageList_ to actually have a translation.
Please let me know if you have any questions.
Thanks,
Lazaro
> Portuguese translation updates

- README.md
Corrected an orthographic  error in the heading
> Typo 'recommended'

- i18n/zh-tw.toml
Add traditional chinese for Taiwan users
> Add zh-tw translation

- i18n/hu.toml
I translated this theme for my website but I think it could be helpful to other people too
> Added Hungarian translation

- README.md
- Added a warning about Hugo binaries not including Go
- Added _From your project's root directory_ to Step 1
> Improve README.md for new users

- i18n/hi.toml
Add support for Hindi language in the Hugo template.
> Translate for Hindi and add to i18n

- layouts/partials/func/style/GetMainCSS.html
> Fix `_styles.css` bad reference in GetMainCSS

- README.md
- layouts/partials/social-share.html
> Make `disable_share` settings on both page and site level

- .gitignore
> Ignore Hugo build lock file

- layouts/partials/func/GetFeaturedImage.html
> Fix support for site config featured image

- i18n/fi.toml
Here's a Finnish translation for your review.
> Finnish Translation 

- exampleSite/content/en/about/index.md
Closes #491
Replaces #492 
Ready for review @regisphilibert
> Update about page ft img to match demo site

- layouts/_default/summary.html
> Change section name to section title in summary

- i18n/ja.toml
Add support for Japanese the Hugo template.
> Translate for Japanese and add to i18n

- README.md
- config.yaml
- exampleSite/content/en/_index.md
- layouts/partials/func/style/GetMainCSS.html
- theme.toml
Check hugo.IsExtended before trying to process scss files
Fixes #541
> Upgrade "minVersion" of theme to 84

- layouts/partials/page-header.html
> Make sure only the title closest to content is an h1,

- README.md
- layouts/partials/social-follow.html
> Add a `rel` option to social registers

- i18n/es.toml
> Added 2 missing i18n es translations

- layouts/partials/social-share.html
Change from /share to /intent/tweet.
More info: https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview
> Change to /intent/tweet (Twitter share link)

- README.md
> Update setup guide link

- README.md
hi, i fixed the demo url. Could yall also fix the demo url in the Repo description? tysm
> Fix broken demo URL

- README.md
Fix for #706
Signed-off-by: Patrick Kollitsch <patrick@davids-neighbour.com>
> docs(fix): proper TOML format for frontmatter sample

- README.md
Whilst following the README, I noticed a couple of the file paths were out of date.
> fix: update filepaths in README.md

- i18n/id.toml
adding indonesian language for i18n.
> theme(i18n): add indonesian language

- netlify.toml
- move environment from production to general build section
- set HUGO_VERSION to 0.128.0 as per hugo.toml
> build(fix): proper configuration for netlify

- README.md
- adds language code to each highlight markdown
- uses consistent TOML for config samples and YAML for frontmatter samples
**Closing issues**
closes #735
> docs: update README.md with markup changes

- layouts/_default/_markup/render-codeblock-goat.html
> theme(fix): set GoAT diagram font size to 1rem

- README.md
> docs(fix): remove ref to 'Production' section in README

- exampleSite/config.toml
> Improve configuration for example site

- i18n/cy.toml
Provides cy.toml i18n file for multilingual sites including the Welsh language (Cymraeg cy).
> Add Welsh i18n translation file (cy.toml)
